# Generated by Django 2.0 on 2018-10-08 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'address_type',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('time', models.TimeField(auto_now=True)),
                ('data', models.DateField(auto_now=True)),
                ('date_and_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backup',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'environment',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Environment')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Environment')),
                ('group_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Group')),
            ],
            options={
                'db_table': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('address_type', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField()),
                ('environment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Environment')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Group')),
            ],
            options={
                'db_table': 'server',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True)),
                ('origin_path', models.TextField(blank=True, null=True)),
                ('destination_path', models.TextField(blank=True, null=True)),
                ('command', models.CharField(blank=True, max_length=256, null=True)),
                ('retention', models.CharField(blank=True, max_length=256, null=True)),
                ('schedule', models.CharField(blank=True, max_length=256, null=True)),
                ('parameters', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Environment')),
                ('group_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Group')),
                ('server_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Server')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('command', models.TextField(blank=True, null=True)),
                ('task', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField()),
                ('createddBy', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'work_type',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='work_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.WorkType'),
        ),
        migrations.AddField(
            model_name='backup',
            name='environment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Environment'),
        ),
        migrations.AddField(
            model_name='backup',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Group'),
        ),
        migrations.AddField(
            model_name='backup',
            name='work_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Work'),
        ),
    ]
